import { BaseModel } from '../../_base/crud';
import { Address } from './address.model';
import { SocialNetworks } from './social-networks.model';

export class User extends BaseModel {
  id: number;
  username: string;
  password: string;
  email: string;
  accessToken: string;
  refreshToken: string;
  roles: number[];
  pic: string;
  name: string;
  description: string;
  price: number;
  message: string;
  timePeriod: string;
  position: string;
  fullname: string;
  occupation: string;
  companyName: string;
  phone: string;
  address: string;
  contact: number;
  city: string;
  state: string;
  country: string;
  zip: number;
  image: string;
  website: string;
  socialNetworks: SocialNetworks;
  topic: string;
  defination: string;
  expiry_date: any;
  _id: string; 
  clear(): void {
    this.id = undefined;
    this.username = '';
    this.password = '';
    this.image = '';
    this.email = '';
    this.roles = [];
    this.fullname = '';
    this.name = '';
    this.accessToken = 'access-token-' + Math.random();
    this.refreshToken = 'access-token-' + Math.random();
    this.pic = './assets/media/users/default.jpg';
    this.occupation = '';
    this.companyName = '';
    this.phone = '';
    this.website = '';
    this.message = '';
    this.timePeriod = '';
    this.position = '';
    this.city = '';
    this.state = '';
    this.country = '';
    // this.contact = '';
    // this.zip = '';
    // this.position = '';
    this.expiry_date = '';
    this.address = ''; //new Address();
    // this.address.clear();
    this.socialNetworks = new SocialNetworks();
    this.socialNetworks.clear();
  }
}
